/* exceptions.c generated by valac 0.16.0, the Vala compiler
 * generated from exceptions.vala, do not modify */

/* Copyright © 2012 Tobias Quathamer
 *
 * This file is part of libisocodes.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>


typedef enum  {
	ISOCODES_ISO_CODES_ERROR_FILE_DOES_NOT_EXIST,
	ISOCODES_ISO_CODES_ERROR_CANNOT_PARSE_FILE,
	ISOCODES_ISO_CODES_ERROR_FILE_DOES_NOT_CONTAIN_ISO_DATA,
	ISOCODES_ISO_CODES_ERROR_CODE_NOT_DEFINED
} isocodesISOCodesError;
#define ISOCODES_ISO_CODES_ERROR isocodes_iso_codes_error_quark ()


GQuark isocodes_iso_codes_error_quark (void);


GQuark isocodes_iso_codes_error_quark (void) {
	return g_quark_from_static_string ("isocodes_iso_codes_error-quark");
}



