/* iso_3166_entry.c generated by valac 0.16.0, the Vala compiler
 * generated from iso_3166_entry.vala, do not modify */

/* Copyright © 2012 Tobias Quathamer
 *
 * This file is part of libisocodes.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <libxml/tree.h>


#define ISOCODES_TYPE_ISO_3166_ENTRY (isocodes_iso_3166_entry_get_type ())
#define ISOCODES_ISO_3166_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ISOCODES_TYPE_ISO_3166_ENTRY, isocodesISO_3166_Entry))
#define ISOCODES_ISO_3166_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ISOCODES_TYPE_ISO_3166_ENTRY, isocodesISO_3166_EntryClass))
#define ISOCODES_IS_ISO_3166_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ISOCODES_TYPE_ISO_3166_ENTRY))
#define ISOCODES_IS_ISO_3166_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ISOCODES_TYPE_ISO_3166_ENTRY))
#define ISOCODES_ISO_3166_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ISOCODES_TYPE_ISO_3166_ENTRY, isocodesISO_3166_EntryClass))

typedef struct _isocodesISO_3166_Entry isocodesISO_3166_Entry;
typedef struct _isocodesISO_3166_EntryClass isocodesISO_3166_EntryClass;
typedef struct _isocodesISO_3166_EntryPrivate isocodesISO_3166_EntryPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _isocodesISO_3166_Entry {
	GObject parent_instance;
	isocodesISO_3166_EntryPrivate * priv;
};

struct _isocodesISO_3166_EntryClass {
	GObjectClass parent_class;
};

struct _isocodesISO_3166_EntryPrivate {
	gchar* _alpha_2_code;
	gchar* _alpha_3_code;
	gchar* _numeric_code;
	gchar* _name;
	gchar* _official_name;
	gchar* _common_name;
};


static gpointer isocodes_iso_3166_entry_parent_class = NULL;

GType isocodes_iso_3166_entry_get_type (void) G_GNUC_CONST;
#define ISOCODES_ISO_3166_ENTRY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), ISOCODES_TYPE_ISO_3166_ENTRY, isocodesISO_3166_EntryPrivate))
enum  {
	ISOCODES_ISO_3166_ENTRY_DUMMY_PROPERTY,
	ISOCODES_ISO_3166_ENTRY_ALPHA_2_CODE,
	ISOCODES_ISO_3166_ENTRY_ALPHA_3_CODE,
	ISOCODES_ISO_3166_ENTRY_NUMERIC_CODE,
	ISOCODES_ISO_3166_ENTRY_NAME,
	ISOCODES_ISO_3166_ENTRY_OFFICIAL_NAME,
	ISOCODES_ISO_3166_ENTRY_COMMON_NAME
};
isocodesISO_3166_Entry* isocodes_iso_3166_entry_new (xmlNode* node);
isocodesISO_3166_Entry* isocodes_iso_3166_entry_construct (GType object_type, xmlNode* node);
void isocodes_iso_3166_entry_set_alpha_2_code (isocodesISO_3166_Entry* self, const gchar* value);
void isocodes_iso_3166_entry_set_alpha_3_code (isocodesISO_3166_Entry* self, const gchar* value);
void isocodes_iso_3166_entry_set_numeric_code (isocodesISO_3166_Entry* self, const gchar* value);
void isocodes_iso_3166_entry_set_name (isocodesISO_3166_Entry* self, const gchar* value);
void isocodes_iso_3166_entry_set_official_name (isocodesISO_3166_Entry* self, const gchar* value);
void isocodes_iso_3166_entry_set_common_name (isocodesISO_3166_Entry* self, const gchar* value);
const gchar* isocodes_iso_3166_entry_get_alpha_2_code (isocodesISO_3166_Entry* self);
const gchar* isocodes_iso_3166_entry_get_alpha_3_code (isocodesISO_3166_Entry* self);
const gchar* isocodes_iso_3166_entry_get_numeric_code (isocodesISO_3166_Entry* self);
const gchar* isocodes_iso_3166_entry_get_name (isocodesISO_3166_Entry* self);
const gchar* isocodes_iso_3166_entry_get_official_name (isocodesISO_3166_Entry* self);
const gchar* isocodes_iso_3166_entry_get_common_name (isocodesISO_3166_Entry* self);
static void isocodes_iso_3166_entry_finalize (GObject* obj);
static void _vala_isocodes_iso_3166_entry_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_isocodes_iso_3166_entry_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


isocodesISO_3166_Entry* isocodes_iso_3166_entry_construct (GType object_type, xmlNode* node) {
	isocodesISO_3166_Entry * self = NULL;
	xmlNode* _tmp0_;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_;
	xmlNode* _tmp3_;
	gchar* _tmp4_ = NULL;
	gchar* _tmp5_;
	xmlNode* _tmp6_;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_;
	xmlNode* _tmp9_;
	gchar* _tmp10_ = NULL;
	gchar* _tmp11_;
	xmlNode* _tmp12_;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_;
	xmlNode* _tmp15_;
	gchar* _tmp16_ = NULL;
	gchar* _tmp17_;
	self = (isocodesISO_3166_Entry*) g_object_new (object_type, NULL);
	_tmp0_ = node;
	_tmp1_ = xmlGetProp (_tmp0_, "alpha_2_code");
	_tmp2_ = _tmp1_;
	isocodes_iso_3166_entry_set_alpha_2_code (self, _tmp2_);
	_g_free0 (_tmp2_);
	_tmp3_ = node;
	_tmp4_ = xmlGetProp (_tmp3_, "alpha_3_code");
	_tmp5_ = _tmp4_;
	isocodes_iso_3166_entry_set_alpha_3_code (self, _tmp5_);
	_g_free0 (_tmp5_);
	_tmp6_ = node;
	_tmp7_ = xmlGetProp (_tmp6_, "numeric_code");
	_tmp8_ = _tmp7_;
	isocodes_iso_3166_entry_set_numeric_code (self, _tmp8_);
	_g_free0 (_tmp8_);
	_tmp9_ = node;
	_tmp10_ = xmlGetProp (_tmp9_, "name");
	_tmp11_ = _tmp10_;
	isocodes_iso_3166_entry_set_name (self, _tmp11_);
	_g_free0 (_tmp11_);
	_tmp12_ = node;
	_tmp13_ = xmlGetProp (_tmp12_, "official_name");
	_tmp14_ = _tmp13_;
	isocodes_iso_3166_entry_set_official_name (self, _tmp14_);
	_g_free0 (_tmp14_);
	_tmp15_ = node;
	_tmp16_ = xmlGetProp (_tmp15_, "common_name");
	_tmp17_ = _tmp16_;
	isocodes_iso_3166_entry_set_common_name (self, _tmp17_);
	_g_free0 (_tmp17_);
	return self;
}


isocodesISO_3166_Entry* isocodes_iso_3166_entry_new (xmlNode* node) {
	return isocodes_iso_3166_entry_construct (ISOCODES_TYPE_ISO_3166_ENTRY, node);
}


const gchar* isocodes_iso_3166_entry_get_alpha_2_code (isocodesISO_3166_Entry* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_alpha_2_code;
	result = _tmp0_;
	return result;
}


void isocodes_iso_3166_entry_set_alpha_2_code (isocodesISO_3166_Entry* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_alpha_2_code);
	self->priv->_alpha_2_code = _tmp1_;
	g_object_notify ((GObject *) self, "alpha-2-code");
}


const gchar* isocodes_iso_3166_entry_get_alpha_3_code (isocodesISO_3166_Entry* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_alpha_3_code;
	result = _tmp0_;
	return result;
}


void isocodes_iso_3166_entry_set_alpha_3_code (isocodesISO_3166_Entry* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_alpha_3_code);
	self->priv->_alpha_3_code = _tmp1_;
	g_object_notify ((GObject *) self, "alpha-3-code");
}


const gchar* isocodes_iso_3166_entry_get_numeric_code (isocodesISO_3166_Entry* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_numeric_code;
	result = _tmp0_;
	return result;
}


void isocodes_iso_3166_entry_set_numeric_code (isocodesISO_3166_Entry* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_numeric_code);
	self->priv->_numeric_code = _tmp1_;
	g_object_notify ((GObject *) self, "numeric-code");
}


const gchar* isocodes_iso_3166_entry_get_name (isocodesISO_3166_Entry* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_name;
	result = _tmp0_;
	return result;
}


void isocodes_iso_3166_entry_set_name (isocodesISO_3166_Entry* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_name);
	self->priv->_name = _tmp1_;
	g_object_notify ((GObject *) self, "name");
}


const gchar* isocodes_iso_3166_entry_get_official_name (isocodesISO_3166_Entry* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_official_name;
	result = _tmp0_;
	return result;
}


void isocodes_iso_3166_entry_set_official_name (isocodesISO_3166_Entry* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_official_name);
	self->priv->_official_name = _tmp1_;
	g_object_notify ((GObject *) self, "official-name");
}


const gchar* isocodes_iso_3166_entry_get_common_name (isocodesISO_3166_Entry* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_common_name;
	result = _tmp0_;
	return result;
}


void isocodes_iso_3166_entry_set_common_name (isocodesISO_3166_Entry* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_common_name);
	self->priv->_common_name = _tmp1_;
	g_object_notify ((GObject *) self, "common-name");
}


static void isocodes_iso_3166_entry_class_init (isocodesISO_3166_EntryClass * klass) {
	isocodes_iso_3166_entry_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (isocodesISO_3166_EntryPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_isocodes_iso_3166_entry_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_isocodes_iso_3166_entry_set_property;
	G_OBJECT_CLASS (klass)->finalize = isocodes_iso_3166_entry_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), ISOCODES_ISO_3166_ENTRY_ALPHA_2_CODE, g_param_spec_string ("alpha-2-code", "alpha-2-code", "alpha-2-code", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ISOCODES_ISO_3166_ENTRY_ALPHA_3_CODE, g_param_spec_string ("alpha-3-code", "alpha-3-code", "alpha-3-code", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ISOCODES_ISO_3166_ENTRY_NUMERIC_CODE, g_param_spec_string ("numeric-code", "numeric-code", "numeric-code", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ISOCODES_ISO_3166_ENTRY_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ISOCODES_ISO_3166_ENTRY_OFFICIAL_NAME, g_param_spec_string ("official-name", "official-name", "official-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), ISOCODES_ISO_3166_ENTRY_COMMON_NAME, g_param_spec_string ("common-name", "common-name", "common-name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void isocodes_iso_3166_entry_instance_init (isocodesISO_3166_Entry * self) {
	self->priv = ISOCODES_ISO_3166_ENTRY_GET_PRIVATE (self);
}


static void isocodes_iso_3166_entry_finalize (GObject* obj) {
	isocodesISO_3166_Entry * self;
	self = ISOCODES_ISO_3166_ENTRY (obj);
	_g_free0 (self->priv->_alpha_2_code);
	_g_free0 (self->priv->_alpha_3_code);
	_g_free0 (self->priv->_numeric_code);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_official_name);
	_g_free0 (self->priv->_common_name);
	G_OBJECT_CLASS (isocodes_iso_3166_entry_parent_class)->finalize (obj);
}


GType isocodes_iso_3166_entry_get_type (void) {
	static volatile gsize isocodes_iso_3166_entry_type_id__volatile = 0;
	if (g_once_init_enter (&isocodes_iso_3166_entry_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (isocodesISO_3166_EntryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) isocodes_iso_3166_entry_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (isocodesISO_3166_Entry), 0, (GInstanceInitFunc) isocodes_iso_3166_entry_instance_init, NULL };
		GType isocodes_iso_3166_entry_type_id;
		isocodes_iso_3166_entry_type_id = g_type_register_static (G_TYPE_OBJECT, "isocodesISO_3166_Entry", &g_define_type_info, 0);
		g_once_init_leave (&isocodes_iso_3166_entry_type_id__volatile, isocodes_iso_3166_entry_type_id);
	}
	return isocodes_iso_3166_entry_type_id__volatile;
}


static void _vala_isocodes_iso_3166_entry_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	isocodesISO_3166_Entry * self;
	self = ISOCODES_ISO_3166_ENTRY (object);
	switch (property_id) {
		case ISOCODES_ISO_3166_ENTRY_ALPHA_2_CODE:
		g_value_set_string (value, isocodes_iso_3166_entry_get_alpha_2_code (self));
		break;
		case ISOCODES_ISO_3166_ENTRY_ALPHA_3_CODE:
		g_value_set_string (value, isocodes_iso_3166_entry_get_alpha_3_code (self));
		break;
		case ISOCODES_ISO_3166_ENTRY_NUMERIC_CODE:
		g_value_set_string (value, isocodes_iso_3166_entry_get_numeric_code (self));
		break;
		case ISOCODES_ISO_3166_ENTRY_NAME:
		g_value_set_string (value, isocodes_iso_3166_entry_get_name (self));
		break;
		case ISOCODES_ISO_3166_ENTRY_OFFICIAL_NAME:
		g_value_set_string (value, isocodes_iso_3166_entry_get_official_name (self));
		break;
		case ISOCODES_ISO_3166_ENTRY_COMMON_NAME:
		g_value_set_string (value, isocodes_iso_3166_entry_get_common_name (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_isocodes_iso_3166_entry_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	isocodesISO_3166_Entry * self;
	self = ISOCODES_ISO_3166_ENTRY (object);
	switch (property_id) {
		case ISOCODES_ISO_3166_ENTRY_ALPHA_2_CODE:
		isocodes_iso_3166_entry_set_alpha_2_code (self, g_value_get_string (value));
		break;
		case ISOCODES_ISO_3166_ENTRY_ALPHA_3_CODE:
		isocodes_iso_3166_entry_set_alpha_3_code (self, g_value_get_string (value));
		break;
		case ISOCODES_ISO_3166_ENTRY_NUMERIC_CODE:
		isocodes_iso_3166_entry_set_numeric_code (self, g_value_get_string (value));
		break;
		case ISOCODES_ISO_3166_ENTRY_NAME:
		isocodes_iso_3166_entry_set_name (self, g_value_get_string (value));
		break;
		case ISOCODES_ISO_3166_ENTRY_OFFICIAL_NAME:
		isocodes_iso_3166_entry_set_official_name (self, g_value_get_string (value));
		break;
		case ISOCODES_ISO_3166_ENTRY_COMMON_NAME:
		isocodes_iso_3166_entry_set_common_name (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



