/* iso_3166.c generated by valac 0.16.0, the Vala compiler
 * generated from iso_3166.vala, do not modify */

/* Copyright © 2012 Tobias Quathamer
 *
 * This file is part of libisocodes.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <libxml/tree.h>
#include <libxml/parser.h>
#include <stdlib.h>
#include <string.h>


#define ISOCODES_TYPE_ISO_CODES (isocodes_iso_codes_get_type ())
#define ISOCODES_ISO_CODES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ISOCODES_TYPE_ISO_CODES, isocodesISO_Codes))
#define ISOCODES_ISO_CODES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ISOCODES_TYPE_ISO_CODES, isocodesISO_CodesClass))
#define ISOCODES_IS_ISO_CODES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ISOCODES_TYPE_ISO_CODES))
#define ISOCODES_IS_ISO_CODES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ISOCODES_TYPE_ISO_CODES))
#define ISOCODES_ISO_CODES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ISOCODES_TYPE_ISO_CODES, isocodesISO_CodesClass))

typedef struct _isocodesISO_Codes isocodesISO_Codes;
typedef struct _isocodesISO_CodesClass isocodesISO_CodesClass;
typedef struct _isocodesISO_CodesPrivate isocodesISO_CodesPrivate;

#define ISOCODES_TYPE_ISO_3166 (isocodes_iso_3166_get_type ())
#define ISOCODES_ISO_3166(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ISOCODES_TYPE_ISO_3166, isocodesISO_3166))
#define ISOCODES_ISO_3166_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ISOCODES_TYPE_ISO_3166, isocodesISO_3166Class))
#define ISOCODES_IS_ISO_3166(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ISOCODES_TYPE_ISO_3166))
#define ISOCODES_IS_ISO_3166_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ISOCODES_TYPE_ISO_3166))
#define ISOCODES_ISO_3166_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ISOCODES_TYPE_ISO_3166, isocodesISO_3166Class))

typedef struct _isocodesISO_3166 isocodesISO_3166;
typedef struct _isocodesISO_3166Class isocodesISO_3166Class;
typedef struct _isocodesISO_3166Private isocodesISO_3166Private;

#define ISOCODES_TYPE_ISO_3166_ENTRY (isocodes_iso_3166_entry_get_type ())
#define ISOCODES_ISO_3166_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), ISOCODES_TYPE_ISO_3166_ENTRY, isocodesISO_3166_Entry))
#define ISOCODES_ISO_3166_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), ISOCODES_TYPE_ISO_3166_ENTRY, isocodesISO_3166_EntryClass))
#define ISOCODES_IS_ISO_3166_ENTRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), ISOCODES_TYPE_ISO_3166_ENTRY))
#define ISOCODES_IS_ISO_3166_ENTRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), ISOCODES_TYPE_ISO_3166_ENTRY))
#define ISOCODES_ISO_3166_ENTRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), ISOCODES_TYPE_ISO_3166_ENTRY, isocodesISO_3166_EntryClass))

typedef struct _isocodesISO_3166_Entry isocodesISO_3166_Entry;
typedef struct _isocodesISO_3166_EntryClass isocodesISO_3166_EntryClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _isocodesISO_Codes {
	GObject parent_instance;
	isocodesISO_CodesPrivate * priv;
	xmlDoc* _xml;
};

struct _isocodesISO_CodesClass {
	GObjectClass parent_class;
};

struct _isocodesISO_3166 {
	isocodesISO_Codes parent_instance;
	isocodesISO_3166Private * priv;
};

struct _isocodesISO_3166Class {
	isocodesISO_CodesClass parent_class;
};

typedef enum  {
	ISOCODES_ISO_CODES_ERROR_FILE_DOES_NOT_EXIST,
	ISOCODES_ISO_CODES_ERROR_CANNOT_PARSE_FILE,
	ISOCODES_ISO_CODES_ERROR_FILE_DOES_NOT_CONTAIN_ISO_DATA,
	ISOCODES_ISO_CODES_ERROR_CODE_NOT_DEFINED
} isocodesISOCodesError;
#define ISOCODES_ISO_CODES_ERROR isocodes_iso_codes_error_quark ()

static gpointer isocodes_iso_3166_parent_class = NULL;

GType isocodes_iso_codes_get_type (void) G_GNUC_CONST;
GType isocodes_iso_3166_get_type (void) G_GNUC_CONST;
enum  {
	ISOCODES_ISO_3166_DUMMY_PROPERTY
};
isocodesISO_3166* isocodes_iso_3166_new (void);
isocodesISO_3166* isocodes_iso_3166_construct (GType object_type);
isocodesISO_Codes* isocodes_iso_codes_new (void);
isocodesISO_Codes* isocodes_iso_codes_construct (GType object_type);
void isocodes_iso_codes_set_standard (isocodesISO_Codes* self, const gchar* value);
void isocodes_iso_codes_set_filepath (isocodesISO_Codes* self, const gchar* value);
GType isocodes_iso_3166_entry_get_type (void) G_GNUC_CONST;
GQuark isocodes_iso_codes_error_quark (void);
isocodesISO_3166_Entry** isocodes_iso_3166_search_code (isocodesISO_3166* self, const gchar* code, int* result_length1, GError** error);
xmlNode** _isocodes_iso_codes_find_code_in_attributes (isocodesISO_Codes* self, gchar** attributes, int attributes_length1, const gchar* code, int* result_length1, GError** error);
isocodesISO_3166_Entry* isocodes_iso_3166_entry_new (xmlNode* node);
isocodesISO_3166_Entry* isocodes_iso_3166_entry_construct (GType object_type, xmlNode* node);
static void _vala_array_add1 (isocodesISO_3166_Entry*** array, int* length, int* size, isocodesISO_3166_Entry* value);
static void isocodes_iso_3166_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


/**
         * Constructor of class.
         * 
         * It is needed to initialize the LibXML parser here.
         */
isocodesISO_3166* isocodes_iso_3166_construct (GType object_type) {
	isocodesISO_3166 * self = NULL;
	self = (isocodesISO_3166*) isocodes_iso_codes_construct (object_type);
	xmlInitParser ();
	isocodes_iso_codes_set_standard ((isocodesISO_Codes*) self, "3166");
	isocodes_iso_codes_set_filepath ((isocodesISO_Codes*) self, "/usr/share/xml/iso-codes/iso_3166.xml");
	return self;
}


isocodesISO_3166* isocodes_iso_3166_new (void) {
	return isocodes_iso_3166_construct (ISOCODES_TYPE_ISO_3166);
}


/**
         * This method tries to locate the given code in the XML file.
         * 
         * @param string Code to search for.
         */
static void _vala_array_add1 (isocodesISO_3166_Entry*** array, int* length, int* size, isocodesISO_3166_Entry* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (isocodesISO_3166_Entry*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


isocodesISO_3166_Entry** isocodes_iso_3166_search_code (isocodesISO_3166* self, const gchar* code, int* result_length1, GError** error) {
	isocodesISO_3166_Entry** result = NULL;
	isocodesISO_3166_Entry** _tmp0_ = NULL;
	isocodesISO_3166_Entry** _result_;
	gint _result__length1;
	gint __result__size_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar** _tmp4_ = NULL;
	gchar** attributes;
	gint attributes_length1;
	gint _attributes_size_;
	const gchar* _tmp5_;
	gchar* _tmp6_ = NULL;
	gchar* _tmp7_;
	gint _tmp8_ = 0;
	xmlNode** _tmp9_ = NULL;
	xmlNode** _tmp10_;
	gint _tmp10__length1;
	xmlNode** s;
	gint s_length1;
	gint _s_size_;
	isocodesISO_3166_Entry** _tmp15_;
	gint _tmp15__length1;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (code != NULL, NULL);
	_tmp0_ = g_new0 (isocodesISO_3166_Entry*, 0 + 1);
	_result_ = _tmp0_;
	_result__length1 = 0;
	__result__size_ = _result__length1;
	_tmp1_ = g_strdup ("alpha_2_code");
	_tmp2_ = g_strdup ("alpha_3_code");
	_tmp3_ = g_strdup ("numeric_code");
	_tmp4_ = g_new0 (gchar*, 3 + 1);
	_tmp4_[0] = _tmp1_;
	_tmp4_[1] = _tmp2_;
	_tmp4_[2] = _tmp3_;
	attributes = _tmp4_;
	attributes_length1 = 3;
	_attributes_size_ = attributes_length1;
	_tmp5_ = code;
	_tmp6_ = g_utf8_strup (_tmp5_, (gssize) (-1));
	_tmp7_ = _tmp6_;
	_tmp9_ = _isocodes_iso_codes_find_code_in_attributes ((isocodesISO_Codes*) self, attributes, attributes_length1, _tmp7_, &_tmp8_, &_inner_error_);
	_tmp10_ = _tmp9_;
	_tmp10__length1 = _tmp8_;
	_g_free0 (_tmp7_);
	s = _tmp10_;
	s_length1 = _tmp10__length1;
	_s_size_ = s_length1;
	if (_inner_error_ != NULL) {
		if (_inner_error_->domain == ISOCODES_ISO_CODES_ERROR) {
			g_propagate_error (error, _inner_error_);
			attributes = (_vala_array_free (attributes, attributes_length1, (GDestroyNotify) g_free), NULL);
			_result_ = (_vala_array_free (_result_, _result__length1, (GDestroyNotify) g_object_unref), NULL);
			return NULL;
		} else {
			attributes = (_vala_array_free (attributes, attributes_length1, (GDestroyNotify) g_free), NULL);
			_result_ = (_vala_array_free (_result_, _result__length1, (GDestroyNotify) g_object_unref), NULL);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	}
	{
		xmlNode** n_collection = NULL;
		gint n_collection_length1 = 0;
		gint _n_collection_size_ = 0;
		gint n_it = 0;
		n_collection = s;
		n_collection_length1 = s_length1;
		for (n_it = 0; n_it < s_length1; n_it = n_it + 1) {
			xmlNode* n = NULL;
			n = n_collection[n_it];
			{
				isocodesISO_3166_Entry** _tmp11_;
				gint _tmp11__length1;
				xmlNode* _tmp12_;
				isocodesISO_3166_Entry* _tmp13_;
				xmlNode* _tmp14_;
				_tmp11_ = _result_;
				_tmp11__length1 = _result__length1;
				_tmp12_ = n;
				_tmp13_ = isocodes_iso_3166_entry_new (_tmp12_);
				_vala_array_add1 (&_result_, &_result__length1, &__result__size_, _tmp13_);
				_tmp14_ = n;
				xmlFreeNode (_tmp14_);
			}
		}
	}
	_tmp15_ = _result_;
	_tmp15__length1 = _result__length1;
	if (result_length1) {
		*result_length1 = _tmp15__length1;
	}
	result = _tmp15_;
	s = (g_free (s), NULL);
	attributes = (_vala_array_free (attributes, attributes_length1, (GDestroyNotify) g_free), NULL);
	return result;
}


static void isocodes_iso_3166_class_init (isocodesISO_3166Class * klass) {
	isocodes_iso_3166_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = isocodes_iso_3166_finalize;
}


static void isocodes_iso_3166_instance_init (isocodesISO_3166 * self) {
}


static void isocodes_iso_3166_finalize (GObject* obj) {
	isocodesISO_3166 * self;
	self = ISOCODES_ISO_3166 (obj);
	xmlCleanupParser ();
	G_OBJECT_CLASS (isocodes_iso_3166_parent_class)->finalize (obj);
}


GType isocodes_iso_3166_get_type (void) {
	static volatile gsize isocodes_iso_3166_type_id__volatile = 0;
	if (g_once_init_enter (&isocodes_iso_3166_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (isocodesISO_3166Class), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) isocodes_iso_3166_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (isocodesISO_3166), 0, (GInstanceInitFunc) isocodes_iso_3166_instance_init, NULL };
		GType isocodes_iso_3166_type_id;
		isocodes_iso_3166_type_id = g_type_register_static (ISOCODES_TYPE_ISO_CODES, "isocodesISO_3166", &g_define_type_info, 0);
		g_once_init_leave (&isocodes_iso_3166_type_id__volatile, isocodes_iso_3166_type_id);
	}
	return isocodes_iso_3166_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



